### ISSUE TITLE
Deployment Checklist

### ISSUE THREAD

**Issue by MitchellShiell** [overture-stack/docs#10]
## Steps to Deployment

These are the order steps to complete the Overture Docs content update

### 1. Conductor Update

- [ ] Update Overture.bio for Conductor
- [ ]  Change Composer repo > Conductor
- [ ] Merge Conductor V2

### 2. Close out all submodule PRs

- [] [Stage](https://github.com/overture-stack/stage/pull/212)
- [] [Arranger:](https://github.com/overture-stack/arranger/pull/892) 
- [] [Song](https://github.com/overture-stack/SONG/pull/857)
- [] [Score](https://github.com/overture-stack/score/pull/482)
- [] [Maestro:](https://github.com/overture-stack/maestro/pull/277)
- [] [Lyric](https://github.com/overture-stack/lyric/pull/106)
- [] [Lectern](https://github.com/overture-stack/lectern/pull/233)
- [] [.github](https://github.com/overture-stack/.github/pull/5)

#### a. Overture Docs

- [x] Readme update
- [ ] Close and merge all `/docs` PRs (see below)
- [ ] Update submodules to main/develop branches
- [ ] Clean up discussion section
- [ ] Test all links
- [ ] Update Funding Page
- [ ] Get Domain and update DNS
- [ ] Configure site on Netlify

#### b. Overture.bio Updates

This will be the last thing to merge

- [ ] Update NavBars & all links to the old documentation pages
- [ ] Replace slack + mentions with github discussions
- [ ] Update the getting started page

**Comment by MitchellShiell** [comment]
## Conductor Roll Out

1. Merge Overture.bio Conductor Update
2. Merge Conductor Update
3. Change Repo Name from composer to conductor
5. Deploy Website on netlify
